name: MAIN_DEPLOY

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 # 安装nodejs，版本指定10
      with:
        node-version: '10.x'
    - name: install configure SCF CLI and deploy
      env: 
        APPID: ${{ secrets.TENCENTCLOUD_APP_ID }} # secrets 提供
        REGION: ap-hongkong
        SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
        SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
      run: |
        cd ~
        sudo pip install scf
        scf configure set --appid $APPID --region $REGION --secret-id $SECRET_ID --secret-key $SECRET_KEY
        cp ./onepoint/test/tencent/template.yaml ./onepoint/
        cd ./onepoint
        scf deploy -f
    - name: install nowsh CLI and deploy
      env: 
        TOKEN: ${{ secrets.NOWSH_TOKEN }} # secrets 提供
      run: |
        cd ~
        sudo npm i -g now
        mkdir ./now
        cp ./onepoint ./now/api/
        cp ./onepoint/test/nowsh/now.json ./now
        cd now
        now --token $TOKEN
